version: "3.9"
services:
  web:
    build:
      dockerfile: rust.Dockerfile
      args:
        # Set the optimalization level and the binary to build in these args
        - build_profile=release
        - build_folder=release
        - compile_target=test_project
    ports:
      - "127.0.0.1:80:3096"
    links:
      - postgres
    env_file:
      - "./code/.env"
  postgres:
    image: postgres
    restart: on-failure
    environment:
      - POSTGRES_USER=testboi
      - POSTGRES_PASSWORD=testboi
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./docker/postgres/postgres-data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"