version: "3.9"
services:
  web:
    build:
      dockerfile: rust.Dockerfile
    ports:
      - "127.0.0.1:80:80"
    links:
      - postgres
  postgres:
    image: postgres
    restart: on-failure
    environment:
      - POSTGRES_USER=testboi
      - POSTGRES_PASSWORD=testboi
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data